### ISSUE TITLE
use app.close() in wrong way

### ISSUE THREAD

**Issue by wsw0108** [eggjs/egg-boilerplate-framework#10]
https://github.com/eggjs/egg-boilerplate-framework/blob/59d9519e80526d7006578331b360ad1e714a4503/boilerplate/test/lib/framework.test.js#L16

It shoule be like below for the first stable version 1.0.0 of Egg.js.
```
after(() => {
  return app.close();
});
```

**Comment by dead-horse** [comment]
`after(() => app.close());` is equal to 

```js
after() => {
  return app.close();
});
```

see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
```
(param1, param2, …, paramN) => expression
// equivalent to: (param1, param2, …, paramN) => { return expression; }
```

**Comment by atian25** [comment]
issue should report to [eggjs/egg](https://github.com/eggjs/egg/issues),  I'll close the issues tab of this repositorie
